### ISSUE TITLE
conv_mnist.py example fails 

### ISSUE THREAD

**Issue by Ondrysak** [BindsNET/bindsnet#350]
`python3 conv_mnist.py` unfortunately this examples crashes for, me `eth_mnist.py` works fine tho 
 here is the output
```
Begin training.

Progress: 0 / 1 (0.0000 seconds)
  0%|                                                                                                                                                               | 0/60000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "conv_mnist.py", line 169, in <module>
    network.run(inputs=inputs, time=time, input_time_dim=1)
  File "/usr/local/lib/python3.6/dist-packages/bindsnet/network/network.py", line 351, in run
    current_inputs[l] = inputs[l][t]
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Comment by Hananel-Hazan** [comment]
Yes, it is related. 
I will try to look in to it in the next couple of days. At the meanwhile, you are welcome to give it a try :-)

**Comment by Hananel-Hazan** [comment]
The script is working.

**Comment by Ondrysak** [comment]
Well on my machine it is not, are you not intrested in reproducing this bug @Hananel-Hazan ?
