### ISSUE TITLE
How to choose convolutional layer and pooling layer parameters

### ISSUE THREAD

**Issue by CHonChou** [BindsNET/bindsnet#402]
My code is as follows：
kernel_size = 4
stride =2
n_filters = 25
kernel_size_pooling =4
stride_pooling = 2
n_filters_pooling =25

conv_size = int((28 - kernel_size + 2 * padding) / stride) + 1
pooling_size=int((28 - kernel_size_pooling ) / stride_pooling) + 1
# Build network.
network = Network()
input_layer = Input(n=784, shape=(1, 28, 28), traces=True)
conv_layer = DiehlAndCookNodes(
    n=n_filters * conv_size * conv_size,
    shape=(n_filters, conv_size, conv_size),
    traces=True,)
conv_conn = Conv2dConnection(
    source=input_layer,
    target=conv_layer,
    kernel_size=kernel_size,
    stride=stride,
    update_rule=PostPre,
    norm=0.4 * kernel_size ** 2,
    nu=[1e-4, 1e-2],
    wmax=1.0,
    )

pooling_layer=DiehlAndCookNodes(n=n_filters_pooling * pooling_size * pooling_size,shape=(n_filters_pooling, pooling_size, pooling_size),traces=True,)
pooling_conn=MaxPool2dConnection(source=conv_layer,target=pooling_layer,kernel_size=kernel_size_pooling,stride=stride_pooling,decay=1,)
output_layer = DiehlAndCookNodes(n=n_neurons,traces=True,rest=-65.0,reset=-60.0,thresh=-52.0,refrac=5,tc_decay=100.0,tc_trace=20.0,theta_plus=theta_plus,tc_theta_decay=tc_theta_decay,)
pooling_output_conn = Connection(
            source=pooling_layer,
            target=output_layer,
            update_rule=PostPre,
            nu=[1e-4, 1e-2],
            reduction=None, )

network.add_layer(input_layer, name="X")
network.add_layer(conv_layer, name="Y")
network.add_layer(pooling_layer, name="Z")
network.add_layer(output_layer, name="M")
network.add_connection(conv_conn, source="X", target="Y")
network.add_connection(pooling_conn, source="Y", target="Z")

Always get an error:
Traceback (most recent call last):
  File "/home/answer/bindsnet/bindsnet-master/examples/mnist/conv_SOM-SNN.py", line 342, in <module>
    network.run(inputs=inputs, time=time, input_time_dim=1)
  File "/home/answer/bindsnet/bindsnet-master/bindsnet/network/network.py", line 345, in run
    current_inputs.update(self._get_inputs())
  File "/home/answer/bindsnet/bindsnet-master/bindsnet/network/network.py", line 236, in _get_inputs
    inputs[c[1]] += self.connections[c].compute(source.s)
RuntimeError: The size of tensor a (13) must match the size of tensor b (5) at non-singleton dimension 3

**Comment by CHonChou** [comment]
A very simple mistake, wrong choice of the number of neurons in the pooling layer
