### ISSUE TITLE
RuntimeError: shape '[32, 4, 8, 8]' is invalid for input of size 262144

### ISSUE THREAD

**Issue by AptX395** [BindsNET/bindsnet#487]
I built a DQN based on SNN with MSTDP learning rule, like this:

```python
self._net = Network(self._dt)
self._input = nodes.Input(shape = (history_len, 84, 84))
self._conv_layer1 = nodes.LIFNodes(shape = (32, 20, 20))
self._conv1 = topology.Conv2dConnection(self._input, self._conv_layer1, kernel_size = 8, stride = 4, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._conv_layer2 = nodes.LIFNodes(shape = (64, 9, 9))
self._conv2 = topology.Conv2dConnection(self._conv_layer1, self._conv_layer2, kernel_size = 4, stride = 2, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._conv_layer3 = nodes.LIFNodes(shape = (64, 7, 7))
self._conv3 = topology.Conv2dConnection(self._conv_layer2, self._conv_layer3, kernel_size = 3, stride = 1, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._fc_layer1 = nodes.LIFNodes(n = 512)
self._fc1 = topology.Connection(self._conv_layer3, self._fc_layer1, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._fc_layer2 = Non_Firing_LIF_Nodes(n = action_num)
self._fc2 = topology.Connection(self._fc_layer1, self._fc_layer2, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
```

But when I run the network as follows:

```python
spike = self._encoder(x).to(self.device)
input = {"input": spike}
self._net.run(input, self._time, one_step = True)
```

I get this error:

```
Traceback (most recent call last):
  File "run.py", line 164, in <module>
    main()
  File "run.py", line 159, in main
    learn(writer)
  File "run.py", line 123, in learn
    model_path = os.path.join(MODEL_DIR, f"{args.model}_{args.env_id}_{time_str}.pkl"))
  File "/home/dwj/Programs/SNN_RL/rl_agent/dqn_agent.py", line 42, in learn
    self._update_main_net(minibatch[0], minibatch[1], minibatch[2], minibatch[3], minibatch[4])
  File "/home/dwj/Programs/SNN_RL/rl_agent/dqn_agent.py", line 137, in _update_main_net
    self._main_net.update(y, q)
  File "/home/dwj/Programs/SNN_RL/neural_network/dsqn_rstdp.py", line 67, in update
    self._net.connections[connection].update(reward = loss)
  File "/usr/local/anaconda3/envs/snn_rl/lib/python3.7/site-packages/bindsnet/network/topology.py", line 374, in update
    super().update(**kwargs)
  File "/usr/local/anaconda3/envs/snn_rl/lib/python3.7/site-packages/bindsnet/network/topology.py", line 102, in update
    self.update_rule.update(**kwargs)
  File "/usr/local/anaconda3/envs/snn_rl/lib/python3.7/site-packages/bindsnet/learning/learning.py", line 669, in _conv2d_connection_update
    self.eligibility = self.eligibility.view(self.connection.w.size())
RuntimeError: shape '[32, 4, 8, 8]' is invalid for input of size 262144
```

It looks like the layer in the network is not in the right shape. But I set up the network according to the structure of DQN.

How should I set the network parameters to solve the above problem?

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 
Cool project!

Its seems you are correct , the Conv2d dimension is not correct . 
Please take a look on the documentation and the examples in particular [batch](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/batch_eth_mnist.py) and on the [convolution example](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py) lines 80 to 90 on how to calculate the right size of the layer.

**Comment by AptX395** [comment]
> Thank you for using BindsNET.
> Cool project!
> 
> Its seems you are correct , the Conv2d dimension is not correct .
> Please take a look on the documentation and the examples in particular [batch](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/batch_eth_mnist.py) and on the [convolution example](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py) lines 80 to 90 on how to calculate the right size of the layer.

Thanks for your reply!

I still have my doubts. The code I've shown above for building the network uses parameters calculated in exactly the same way as in the [convolution example](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py) lines 80 to 90.

Specifically, it looks like this:

The input to the network is a batch of preprocessed images with the shape `(32, 4, 84, 84)`, corresponding to `(batch_size, channel, height, width)`.

The formula for the output of the convolutional layer is as follows: (copied from the [convolution example](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py) lines 80 to 90)

```python
conv_size = int((28 - kernel_size + 2 * padding) / stride) + 1
```

The calculation process is as follows:

```python
conv_size1 = int((84 - 8 + 2 * 0) / 4) + 1    # conv_size1 = 20
conv_size2 = int((20 - 4 + 2 * 0) / 2) + 1    # conv_size2 = 9
conv_size3 = int((9 - 3 + 2 * 0) / 1) + 1      #conv_size3 = 7
```

So I set up the network parameters like this:

```python
# The number of filters in the three convolution layers are 32, 64, 64, respectively.
self._net = Network(self._dt)
self._input = nodes.Input(shape = (history_len, 84, 84))
self._conv_layer1 = nodes.LIFNodes(shape = (32, 20, 20))
self._conv1 = topology.Conv2dConnection(self._input, self._conv_layer1, kernel_size = 8, stride = 4, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._conv_layer2 = nodes.LIFNodes(shape = (64, 9, 9))
self._conv2 = topology.Conv2dConnection(self._conv_layer1, self._conv_layer2, kernel_size = 4, stride = 2, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._conv_layer3 = nodes.LIFNodes(shape = (64, 7, 7))
self._conv3 = topology.Conv2dConnection(self._conv_layer2, self._conv_layer3, kernel_size = 3, stride = 1, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._fc_layer1 = nodes.LIFNodes(n = 512)
self._fc1 = topology.Connection(self._conv_layer3, self._fc_layer1, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
self._fc_layer2 = Non_Firing_LIF_Nodes(n = action_num)
self._fc2 = topology.Connection(self._fc_layer1, self._fc_layer2, update_rule = MSTDP, nu = learning_rate, wmin = 0, wmax = 1)
```

The above calculation procedure does not seem to have an error. Could there be other reasons for the RuntimeError?

Thank you for your help!
